# Generated by Django 6.1 on 2026-08-27 13:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0003_user_profile_photo"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="role",
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
