# Generated by Django 6.1 on 2026-09-07 12:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_department_user_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='deleted_by',
            field=models.ManyToManyField(blank=True, related_name='deleted_chats', to=settings.AUTH_USER_MODEL),
        ),
    ]
